spring.application.name=hello_hub

# MongoDB
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://suyama:s12345678@cluster0.ryacwkx.mongodb.net/EduNova?retryWrites=true&w=majority&appName=Cluster0}

# Google OAuth2 client registration
spring.security.oauth2.client.registration.google.client-id=835157887365-ukojkv6n193krha430l6hjdj0s69ade3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# Application security
app.frontend.redirect-uri=${APP_FRONTEND_REDIRECT_URI:http://localhost:5173}
app.jwt.secret=${APP_JWT_SECRET:P2fz5XPr6NcqAVM+gojrhbNoQIALSbpOWp1CEJbW7rOd0M6gIJ4qm2IbQ+BbZP4pb/8eXL683ielZFKRGfIlJQ==}
app.jwt.expiration-ms=${APP_JWT_EXPIRATION_MS:86400000}
